//! Self-signed certificate generation for application credentials.
//!
//! Generates an RSA-2048 key pair and a self-signed X.509 certificate. The
//! public certificate is uploaded to an app registration as a verify-only key
//! credential; the private key is returned to the user once and never
//! persisted. RSA (not ECDSA) is used because Microsoft Entra client
//! assertions require it. The key is generated by `rcgen` on its `aws_lc_rs`
//! backend (already in the tree via rustls), which keeps the `rsa` crate
//! (RUSTSEC-2023-0071) out of the dependency graph.
//!
//! Both thumbprints are digested by that same `aws-lc-rs`. The SHA-1 one is the
//! load-bearing value: Entra derives `customKeyIdentifier` as SHA-1 of the DER,
//! so it is what the Credentials tab, the Entra portal, and a client
//! assertion's `x5t` all show. Showing anything else here means the operator
//! cannot find the certificate they just minted. SHA-1 is used **only** as that
//! identifier, never as a security primitive — hence aws-lc-rs's deliberately
//! named `SHA1_FOR_LEGACY_USE_ONLY`.

use aws_lc_rs::digest;
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use time::{Duration, OffsetDateTime};
use zeroize::Zeroize;

pub struct GeneratedCert {
    /// Base64-encoded DER of the certificate — the `key` for a Graph key credential.
    pub cert_der_base64: String,
    pub cert_pem: String,
    /// PKCS#8 PEM of the RSA private key. Sensitive: surfaced once, never
    /// stored. Zeroized on drop so the PEM bytes do not linger on the heap
    /// after the value is returned to the caller (which clones into the IPC
    /// reply path and drops the original almost immediately).
    pub private_key_pem: String,
    /// SHA-1 thumbprint (uppercase hex) of the cert DER — the same value Entra
    /// derives into `customKeyIdentifier`, so the reveal and the Credentials
    /// tab show one identical string for one certificate.
    pub thumbprint: String,
    /// SHA-256 thumbprint (uppercase hex) of the same DER, for operators who
    /// verify or pin on the stronger digest.
    pub thumbprint_sha256: String,
    /// Certificate validity end, mirrored onto the Graph key credential.
    pub not_after: OffsetDateTime,
}

impl Drop for GeneratedCert {
    fn drop(&mut self) {
        self.private_key_pem.zeroize();
    }
}

impl std::fmt::Debug for GeneratedCert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GeneratedCert")
            .field("cert_der_base64", &"…")
            .field("cert_pem", &"…")
            .field("private_key_pem", &"<redacted>")
            .field("thumbprint", &self.thumbprint)
            .field("thumbprint_sha256", &self.thumbprint_sha256)
            .field("not_after", &self.not_after)
            .finish()
    }
}

/// Maximum certificate validity in days. Microsoft Entra rejects key
/// credentials with `endDateTime` more than ~3 years in the future, and most
/// AAD app-credential rotation policies tighten that further. We enforce the
/// upper bound here so a caller asking for "10 years" is told no rather than
/// silently issued a 3-year cert.
pub const MAX_VALIDITY_DAYS: i64 = 1095;

/// Generates a self-signed RSA certificate with subject `CN=<common_name>` and
/// the given validity in days. Returns an error for any validity outside
/// `1..=MAX_VALIDITY_DAYS` so a user-supplied value is never silently
/// truncated.
pub fn generate_self_signed(
    common_name: &str,
    validity_days: i64,
) -> Result<GeneratedCert, String> {
    if !(1..=MAX_VALIDITY_DAYS).contains(&validity_days) {
        return Err(format!(
            "validity must be between 1 and {MAX_VALIDITY_DAYS} days (got {validity_days})"
        ));
    }
    let cn = common_name.trim();
    if cn.is_empty() {
        return Err("certificate subject (common name) is required".into());
    }

    let key_pair =
        rcgen::KeyPair::generate_rsa_for(&rcgen::PKCS_RSA_SHA256, rcgen::RsaKeySize::_2048)
            .map_err(|e| format!("RSA key generation failed: {e}"))?;
    // PKCS#8 PEM of the private key — surfaced once to the user, never persisted.
    let pkcs8_pem = key_pair.serialize_pem();

    let mut params = rcgen::CertificateParams::new(Vec::<String>::new())
        .map_err(|e| format!("certificate params failed: {e}"))?;
    let mut dn = rcgen::DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, cn);
    params.distinguished_name = dn;
    let now = OffsetDateTime::now_utc();
    // Backdate slightly to tolerate clock skew between client and Entra.
    params.not_before = now - Duration::hours(1);
    let not_after = now + Duration::days(validity_days);
    params.not_after = not_after;

    let cert = params
        .self_signed(&key_pair)
        .map_err(|e| format!("self-signing failed: {e}"))?;
    let der = cert.der();
    let der_bytes: &[u8] = der.as_ref();

    // SHA-1 first because it is the one an operator acts on: it is what Entra
    // returns as `customKeyIdentifier`, what the portal's Thumbprint column
    // shows, and what a client assertion carries as `x5t`.
    let thumbprint = azapptoolkit_core::thumbprint::hex_upper(
        digest::digest(&digest::SHA1_FOR_LEGACY_USE_ONLY, der_bytes).as_ref(),
    );
    let thumbprint_sha256 = azapptoolkit_core::thumbprint::hex_upper(
        digest::digest(&digest::SHA256, der_bytes).as_ref(),
    );

    Ok(GeneratedCert {
        cert_der_base64: STANDARD.encode(der_bytes),
        cert_pem: cert.pem(),
        private_key_pem: pkcs8_pem,
        thumbprint,
        thumbprint_sha256,
        not_after,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_rsa_self_signed_with_expected_fields() {
        let c = generate_self_signed("My App", 365).unwrap();
        assert!(c.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(c.private_key_pem.contains("BEGIN PRIVATE KEY"));
        assert!(!c.cert_der_base64.is_empty());
        // SHA-1 thumbprint is 20 bytes -> 40 hex chars; SHA-256 is 64. Both
        // uppercase, both separator-free.
        assert_eq!(c.thumbprint.len(), 40);
        assert_eq!(c.thumbprint_sha256.len(), 64);
        for tp in [&c.thumbprint, &c.thumbprint_sha256] {
            assert!(
                tp.chars()
                    .all(|ch| ch.is_ascii_hexdigit() && !ch.is_ascii_lowercase()),
                "{tp}"
            );
        }
        assert!(c.not_after > OffsetDateTime::now_utc());
    }

    /// The invariant the reveal modal exists to satisfy: the thumbprint shown
    /// right after generating must be the *same string* the Credentials tab
    /// shows once Entra hands the certificate back.
    ///
    /// Entra derives `customKeyIdentifier` as base64 of the DER's SHA-1, and the
    /// tab renders it through `core::thumbprint::canonical`. Reproducing both
    /// halves here pins the agreement end to end; the two used to be SHA-256 and
    /// SHA-1 respectively, so they could never match.
    #[test]
    fn the_revealed_thumbprint_is_what_entra_will_report_for_the_same_cert() {
        let c = generate_self_signed("My App", 365).unwrap();
        let der = STANDARD.decode(&c.cert_der_base64).unwrap();

        // What Graph will serialize into `customKeyIdentifier`.
        let custom_key_identifier =
            STANDARD.encode(digest::digest(&digest::SHA1_FOR_LEGACY_USE_ONLY, &der).as_ref());

        assert_eq!(
            azapptoolkit_core::thumbprint::canonical(&custom_key_identifier).as_deref(),
            Some(c.thumbprint.as_str()),
            "the reveal and the Credentials tab must show one identical string",
        );
        assert_ne!(
            c.thumbprint, c.thumbprint_sha256,
            "premise: the two digests differ, so showing the wrong one is visible",
        );
    }

    #[test]
    fn rejects_empty_common_name() {
        assert!(generate_self_signed("   ", 365).is_err());
    }

    #[test]
    fn rejects_validity_below_one_day() {
        assert!(generate_self_signed("App", 0).is_err());
        assert!(generate_self_signed("App", -5).is_err());
    }

    #[test]
    fn rejects_validity_above_max() {
        let r = generate_self_signed("App", MAX_VALIDITY_DAYS + 1);
        assert!(r.is_err());
        // Error mentions the limit so a UI can present an actionable message.
        assert!(r.unwrap_err().contains(&MAX_VALIDITY_DAYS.to_string()));
    }

    #[test]
    fn accepts_validity_at_boundaries() {
        assert!(generate_self_signed("App", 1).is_ok());
        assert!(generate_self_signed("App", MAX_VALIDITY_DAYS).is_ok());
    }
}
