//! Self-signed certificate generation for application credentials.
//!
//! Generates an RSA-2048 key pair and a self-signed X.509 certificate. The
//! public certificate is uploaded to an app registration as a verify-only key
//! credential; the private key is returned to the user once and never
//! persisted. RSA (not ECDSA) is used because Microsoft Entra client
//! assertions require it. The key is generated by `rcgen` on its `aws_lc_rs`
//! backend (already in the tree via rustls), which keeps the `rsa` crate
//! (RUSTSEC-2023-0071) out of the dependency graph.

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use sha2::{Digest, Sha256};
use time::{Duration, OffsetDateTime};
use zeroize::Zeroize;

pub struct GeneratedCert {
    /// Base64-encoded DER of the certificate — the `key` for a Graph key credential.
    pub cert_der_base64: String,
    pub cert_pem: String,
    /// PKCS#8 PEM of the RSA private key. Sensitive: surfaced once, never
    /// stored. Zeroized on drop so the PEM bytes do not linger on the heap
    /// after the value is returned to the caller (which clones into the IPC
    /// reply path and drops the original almost immediately).
    pub private_key_pem: String,
    /// SHA-256 thumbprint (uppercase hex) — computed from the cert DER below.
    pub thumbprint: String,
    /// Certificate validity end, mirrored onto the Graph key credential.
    pub not_after: OffsetDateTime,
}

impl Drop for GeneratedCert {
    fn drop(&mut self) {
        self.private_key_pem.zeroize();
    }
}

impl std::fmt::Debug for GeneratedCert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GeneratedCert")
            .field("cert_der_base64", &"…")
            .field("cert_pem", &"…")
            .field("private_key_pem", &"<redacted>")
            .field("thumbprint", &self.thumbprint)
            .field("not_after", &self.not_after)
            .finish()
    }
}

/// Maximum certificate validity in days. Microsoft Entra rejects key
/// credentials with `endDateTime` more than ~3 years in the future, and most
/// AAD app-credential rotation policies tighten that further. We enforce the
/// upper bound here so a caller asking for "10 years" is told no rather than
/// silently issued a 3-year cert.
pub const MAX_VALIDITY_DAYS: i64 = 1095;

/// Generates a self-signed RSA certificate with subject `CN=<common_name>` and
/// the given validity in days. Returns an error for any validity outside
/// `1..=MAX_VALIDITY_DAYS` so a user-supplied value is never silently
/// truncated.
pub fn generate_self_signed(
    common_name: &str,
    validity_days: i64,
) -> Result<GeneratedCert, String> {
    if !(1..=MAX_VALIDITY_DAYS).contains(&validity_days) {
        return Err(format!(
            "validity must be between 1 and {MAX_VALIDITY_DAYS} days (got {validity_days})"
        ));
    }
    let cn = common_name.trim();
    if cn.is_empty() {
        return Err("certificate subject (common name) is required".into());
    }

    let key_pair =
        rcgen::KeyPair::generate_rsa_for(&rcgen::PKCS_RSA_SHA256, rcgen::RsaKeySize::_2048)
            .map_err(|e| format!("RSA key generation failed: {e}"))?;
    // PKCS#8 PEM of the private key — surfaced once to the user, never persisted.
    let pkcs8_pem = key_pair.serialize_pem();

    let mut params = rcgen::CertificateParams::new(Vec::<String>::new())
        .map_err(|e| format!("certificate params failed: {e}"))?;
    let mut dn = rcgen::DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, cn);
    params.distinguished_name = dn;
    let now = OffsetDateTime::now_utc();
    // Backdate slightly to tolerate clock skew between client and Entra.
    params.not_before = now - Duration::hours(1);
    let not_after = now + Duration::days(validity_days);
    params.not_after = not_after;

    let cert = params
        .self_signed(&key_pair)
        .map_err(|e| format!("self-signing failed: {e}"))?;
    let der = cert.der();
    let der_bytes: &[u8] = der.as_ref();

    let mut hasher = Sha256::new();
    hasher.update(der_bytes);
    let thumbprint = hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02X}"))
        .collect::<String>();

    Ok(GeneratedCert {
        cert_der_base64: STANDARD.encode(der_bytes),
        cert_pem: cert.pem(),
        private_key_pem: pkcs8_pem,
        thumbprint,
        not_after,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_rsa_self_signed_with_expected_fields() {
        let c = generate_self_signed("My App", 365).unwrap();
        assert!(c.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(c.private_key_pem.contains("BEGIN PRIVATE KEY"));
        assert!(!c.cert_der_base64.is_empty());
        // SHA-256 thumbprint is 32 bytes -> 64 hex chars, uppercase.
        assert_eq!(c.thumbprint.len(), 64);
        assert!(
            c.thumbprint
                .chars()
                .all(|ch| ch.is_ascii_hexdigit() && !ch.is_ascii_lowercase())
        );
        assert!(c.not_after > OffsetDateTime::now_utc());
    }

    #[test]
    fn rejects_empty_common_name() {
        assert!(generate_self_signed("   ", 365).is_err());
    }

    #[test]
    fn rejects_validity_below_one_day() {
        assert!(generate_self_signed("App", 0).is_err());
        assert!(generate_self_signed("App", -5).is_err());
    }

    #[test]
    fn rejects_validity_above_max() {
        let r = generate_self_signed("App", MAX_VALIDITY_DAYS + 1);
        assert!(r.is_err());
        // Error mentions the limit so a UI can present an actionable message.
        assert!(r.unwrap_err().contains(&MAX_VALIDITY_DAYS.to_string()));
    }

    #[test]
    fn accepts_validity_at_boundaries() {
        assert!(generate_self_signed("App", 1).is_ok());
        assert!(generate_self_signed("App", MAX_VALIDITY_DAYS).is_ok());
    }
}
