//! Self-signed certificate generation for application credentials.
//!
//! Generates an RSA-2048 key pair and a self-signed X.509 certificate. The
//! public certificate is uploaded to an app registration as a verify-only key
//! credential; the private key is returned to the user once and never
//! persisted. RSA (not ECDSA) is used because Microsoft Entra client
//! assertions require it. The key is generated by `rcgen` on its `aws_lc_rs`
//! backend (already in the tree via rustls), which keeps the `rsa` crate
//! (RUSTSEC-2023-0071) out of the dependency graph.
//!
//! Both thumbprints are digested by that same `aws-lc-rs`. The SHA-1 one is the
//! load-bearing value: Entra derives `customKeyIdentifier` as SHA-1 of the DER,
//! so it is what the Credentials tab, the Entra portal, and a client
//! assertion's `x5t` all show. Showing anything else here means the operator
//! cannot find the certificate they just minted. SHA-1 is used **only** as that
//! identifier, never as a security primitive — hence aws-lc-rs's deliberately
//! named `SHA1_FOR_LEGACY_USE_ONLY`.

use aws_lc_rs::digest;
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use time::{Duration, OffsetDateTime};
use zeroize::Zeroize;

pub struct GeneratedCert {
    /// Base64-encoded DER of the certificate — the `key` for a Graph key credential.
    pub cert_der_base64: String,
    pub cert_pem: String,
    /// PKCS#8 PEM of the RSA private key. Sensitive: surfaced once, never
    /// stored. Zeroized on drop so the PEM bytes do not linger on the heap
    /// after the value is returned to the caller (which clones into the IPC
    /// reply path and drops the original almost immediately).
    pub private_key_pem: String,
    /// PKCS#12 (.pfx) bundle: this same certificate and this same private key,
    /// encrypted under `pfx_password`. Not an alternative identity — one key in
    /// two encodings, so the public half Entra now holds authenticates either.
    /// The PEM above stays primary (Linux/macOS hosts, Python/Node MSAL, the
    /// Azure SDK's `certificate_path`, a Key Vault import); this is the form
    /// Windows takes, via `Import-PfxCertificate`.
    pub pfx_der: Vec<u8>,
    /// The password protecting `pfx_der`, generated here rather than asked for.
    /// The bundle is worth exactly the private key to anyone holding this, so
    /// it gets the private key's treatment: surfaced once, never persisted,
    /// zeroized on drop, redacted from `Debug`.
    pub pfx_password: String,
    /// SHA-1 thumbprint (uppercase hex) of the cert DER — the same value Entra
    /// derives into `customKeyIdentifier`, so the reveal and the Credentials
    /// tab show one identical string for one certificate.
    pub thumbprint: String,
    /// SHA-256 thumbprint (uppercase hex) of the same DER, for operators who
    /// verify or pin on the stronger digest.
    pub thumbprint_sha256: String,
    /// Certificate validity end, mirrored onto the Graph key credential.
    pub not_after: OffsetDateTime,
}

impl Drop for GeneratedCert {
    fn drop(&mut self) {
        self.private_key_pem.zeroize();
        // The bundle and its password are the same secret in another wrapper.
        self.pfx_password.zeroize();
        self.pfx_der.zeroize();
    }
}

impl std::fmt::Debug for GeneratedCert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GeneratedCert")
            .field("cert_der_base64", &"…")
            .field("cert_pem", &"…")
            .field("private_key_pem", &"<redacted>")
            .field("pfx_der", &"<redacted>")
            .field("pfx_password", &"<redacted>")
            .field("thumbprint", &self.thumbprint)
            .field("thumbprint_sha256", &self.thumbprint_sha256)
            .field("not_after", &self.not_after)
            .finish()
    }
}

/// Maximum certificate validity in days. Microsoft Entra rejects key
/// credentials with `endDateTime` more than ~3 years in the future, and most
/// AAD app-credential rotation policies tighten that further. We enforce the
/// upper bound here so a caller asking for "10 years" is told no rather than
/// silently issued a 3-year cert.
pub const MAX_VALIDITY_DAYS: i64 = 1095;

/// Generates a self-signed RSA certificate with subject `CN=<common_name>` and
/// the given validity in days. Returns an error for any validity outside
/// `1..=MAX_VALIDITY_DAYS` so a user-supplied value is never silently
/// truncated.
pub fn generate_self_signed(
    common_name: &str,
    validity_days: i64,
) -> Result<GeneratedCert, String> {
    if !(1..=MAX_VALIDITY_DAYS).contains(&validity_days) {
        return Err(format!(
            "validity must be between 1 and {MAX_VALIDITY_DAYS} days (got {validity_days})"
        ));
    }
    let cn = common_name.trim();
    if cn.is_empty() {
        return Err("certificate subject (common name) is required".into());
    }

    let key_pair =
        rcgen::KeyPair::generate_rsa_for(&rcgen::PKCS_RSA_SHA256, rcgen::RsaKeySize::_2048)
            .map_err(|e| format!("RSA key generation failed: {e}"))?;
    // PKCS#8 PEM of the private key — surfaced once to the user, never persisted.
    let pkcs8_pem = key_pair.serialize_pem();

    let mut params = rcgen::CertificateParams::new(Vec::<String>::new())
        .map_err(|e| format!("certificate params failed: {e}"))?;
    let mut dn = rcgen::DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, cn);
    params.distinguished_name = dn;
    let now = OffsetDateTime::now_utc();
    // Backdate slightly to tolerate clock skew between client and Entra.
    params.not_before = now - Duration::hours(1);
    let not_after = now + Duration::days(validity_days);
    params.not_after = not_after;

    let cert = params
        .self_signed(&key_pair)
        .map_err(|e| format!("self-signing failed: {e}"))?;
    let der = cert.der();
    let der_bytes: &[u8] = der.as_ref();

    // SHA-1 first because it is the one an operator acts on: it is what Entra
    // returns as `customKeyIdentifier`, what the portal's Thumbprint column
    // shows, and what a client assertion carries as `x5t`.
    // Bound once, not digested twice: the raw bytes are also the PKCS#12
    // `localKeyId` below, and deriving the same digest in two places is how the
    // two would eventually disagree.
    let sha1 = digest::digest(&digest::SHA1_FOR_LEGACY_USE_ONLY, der_bytes);
    let thumbprint = azapptoolkit_core::thumbprint::hex_upper(sha1.as_ref());
    let thumbprint_sha256 = azapptoolkit_core::thumbprint::hex_upper(
        digest::digest(&digest::SHA256, der_bytes).as_ref(),
    );

    // `serialized_der()` borrows the PKCS#8 bytes rcgen already holds rather
    // than handing back an owned copy, so the private key does not land on a
    // second allocation that would need its own zeroization.
    let pfx_password = random_pfx_password();
    let pfx_der = build_pfx(
        der_bytes,
        key_pair.serialized_der(),
        sha1.as_ref(),
        cn,
        &pfx_password,
    )?;

    Ok(GeneratedCert {
        cert_der_base64: STANDARD.encode(der_bytes),
        cert_pem: cert.pem(),
        private_key_pem: pkcs8_pem,
        pfx_der,
        pfx_password,
        thumbprint,
        thumbprint_sha256,
        not_after,
    })
}

/// A random password for the generated PKCS#12 bundle.
///
/// 24 bytes of OS randomness as unpadded base64url: 192 bits in 32 characters,
/// unbiased by construction — no modulo folding over a hand-rolled alphabet.
///
/// The alphabet is the point. `A-Za-z0-9-_` has no `+`, `/` or `=`, so the
/// string survives a PowerShell `ConvertTo-SecureString`, an `openssl -passin
/// pass:` argument, a URL and a YAML value without quoting games — and it is
/// pure ASCII, which matters because a PKCS#12 password is encoded as a
/// BMPString (UTF-16BE) and ASCII is the range every reader agrees on.
///
/// `OsRng` rather than the `thread_rng()` `commands::guid` uses: both are
/// CSPRNGs, but this is a credential, and the OS source has no reseeding or
/// thread-local state to reason about.
fn random_pfx_password() -> String {
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use rand::RngCore as _;
    use rand::rngs::OsRng;

    let mut bytes = [0u8; 24];
    OsRng.fill_bytes(&mut bytes);
    let password = URL_SAFE_NO_PAD.encode(bytes);
    bytes.zeroize();
    password
}

/// Bundles the certificate and its PKCS#8 private key into a password-protected
/// PKCS#12 blob (PBES2 / AES-256-CBC, HMAC-SHA256 MAC).
///
/// `local_key_id` must be the certificate's **SHA-1 digest** — the same 20 bytes
/// Entra derives into `customKeyIdentifier` and the portal prints as the
/// Thumbprint. Windows' PKCS#12 reader binds the key bag to the certificate bag
/// through this attribute: get it wrong and `Import-PfxCertificate` *succeeds*
/// with `HasPrivateKey = False`, which the operator discovers much later, when a
/// client assertion won't sign.
///
/// The profile is set explicitly even though it is the writer's current default.
/// A default that quietly moved to a legacy PBE would downgrade every bundle we
/// mint, in a version bump with no diff to review.
fn build_pfx(
    cert_der: &[u8],
    key_pkcs8_der: &[u8],
    local_key_id: &[u8],
    alias: &str,
    password: &str,
) -> Result<Vec<u8>, String> {
    use p12_keystore::{
        Certificate, EncryptionAlgorithm, KeyStore, KeyStoreEntry, MacAlgorithm, PrivateKeyChain,
    };

    let cert = Certificate::from_der(cert_der)
        .map_err(|e| format!("PKCS#12 certificate encoding failed: {e}"))?;
    // Both arguments are `AsRef<[u8]>` in the order (key, id), so transposing
    // them compiles and yields a bundle no reader can open. That is what
    // `the_pfx_holds_the_same_key_as_the_revealed_pem` is pinned against.
    let chain = PrivateKeyChain::new(key_pkcs8_der, local_key_id, [cert]);

    let mut store = KeyStore::new();
    store.add_entry(alias, KeyStoreEntry::PrivateKeyChain(chain));
    store
        .writer(password)
        .encryption_algorithm(EncryptionAlgorithm::PbeWithHmacSha256AndAes256)
        .mac_algorithm(MacAlgorithm::HmacSha256)
        // Iterations stay at the crate default (10 000). The password above
        // carries ~192 bits, so the KDF work factor is not the control doing
        // the work here, and a modest count keeps older readers happy.
        .write()
        .map_err(|e| format!("PKCS#12 write failed: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_rsa_self_signed_with_expected_fields() {
        let c = generate_self_signed("My App", 365).unwrap();
        assert!(c.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(c.private_key_pem.contains("BEGIN PRIVATE KEY"));
        assert!(!c.cert_der_base64.is_empty());
        // SHA-1 thumbprint is 20 bytes -> 40 hex chars; SHA-256 is 64. Both
        // uppercase, both separator-free.
        assert_eq!(c.thumbprint.len(), 40);
        assert_eq!(c.thumbprint_sha256.len(), 64);
        for tp in [&c.thumbprint, &c.thumbprint_sha256] {
            assert!(
                tp.chars()
                    .all(|ch| ch.is_ascii_hexdigit() && !ch.is_ascii_lowercase()),
                "{tp}"
            );
        }
        assert!(c.not_after > OffsetDateTime::now_utc());
    }

    /// The invariant the reveal modal exists to satisfy: the thumbprint shown
    /// right after generating must be the *same string* the Credentials tab
    /// shows once Entra hands the certificate back.
    ///
    /// Entra derives `customKeyIdentifier` as base64 of the DER's SHA-1, and the
    /// tab renders it through `core::thumbprint::canonical`. Reproducing both
    /// halves here pins the agreement end to end; the two used to be SHA-256 and
    /// SHA-1 respectively, so they could never match.
    #[test]
    fn the_revealed_thumbprint_is_what_entra_will_report_for_the_same_cert() {
        let c = generate_self_signed("My App", 365).unwrap();
        let der = STANDARD.decode(&c.cert_der_base64).unwrap();

        // What Graph will serialize into `customKeyIdentifier`.
        let custom_key_identifier =
            STANDARD.encode(digest::digest(&digest::SHA1_FOR_LEGACY_USE_ONLY, &der).as_ref());

        assert_eq!(
            azapptoolkit_core::thumbprint::canonical(&custom_key_identifier).as_deref(),
            Some(c.thumbprint.as_str()),
            "the reveal and the Credentials tab must show one identical string",
        );
        assert_ne!(
            c.thumbprint, c.thumbprint_sha256,
            "premise: the two digests differ, so showing the wrong one is visible",
        );
    }

    /// Strips PKCS#8 PEM armour back to the DER the PEM encodes.
    fn pem_body(pem: &str) -> Vec<u8> {
        let b64: String = pem
            .lines()
            .filter(|l| !l.starts_with("-----"))
            .collect::<Vec<_>>()
            .concat();
        STANDARD.decode(b64).expect("PEM body is base64")
    }

    fn open_pfx(c: &GeneratedCert) -> p12_keystore::KeyStore {
        p12_keystore::KeyStore::from_pkcs12(&c.pfx_der, &c.pfx_password)
            .expect("the bundle must open under the password shown beside it")
    }

    /// The claim the whole feature rests on: the `.pfx` and the PEM reveal are
    /// **one identity**, not two.
    ///
    /// An operator imports the bundle on Windows and hands the PEM to a Linux
    /// node; the single public half Entra holds has to authenticate both. If a
    /// refactor ever mints a second key pair for the bundle, or transposes
    /// `PrivateKeyChain::new`'s `(key, local_key_id)` — both `AsRef<[u8]>`, so
    /// both compile — this is what fails.
    #[test]
    fn the_generated_pfx_is_the_same_identity_as_the_revealed_pem() {
        let c = generate_self_signed("My App", 365).unwrap();
        let ks = open_pfx(&c);
        let (alias, chain) = ks.private_key_chain().expect("a private key bag");

        assert_eq!(alias, "My App", "the bag is aliased by the subject");
        assert_eq!(
            chain.key(),
            pem_body(&c.private_key_pem).as_slice(),
            "the bundled key must BE the revealed key, not another one",
        );
        assert_eq!(
            chain.chain().len(),
            1,
            "a self-signed leaf and nothing else",
        );
        assert_eq!(
            chain.chain()[0].as_der(),
            STANDARD.decode(&c.cert_der_base64).unwrap().as_slice(),
            "the bundled certificate must be the one uploaded to Entra",
        );
    }

    /// `localKeyId` is what binds the key bag to the certificate bag. Windows
    /// imports a mismatched pair *successfully*, with `HasPrivateKey = False` —
    /// a silent failure surfacing much later as an assertion that won't sign.
    ///
    /// Pinning it to the SHA-1 thumbprint also extends the 0.28.2 rule inward:
    /// one certificate, one string, everywhere it appears.
    #[test]
    fn the_pfx_local_key_id_is_the_certificate_thumbprint() {
        let c = generate_self_signed("My App", 365).unwrap();
        let ks = open_pfx(&c);
        let (_, chain) = ks.private_key_chain().unwrap();
        assert_eq!(
            azapptoolkit_core::thumbprint::hex_upper(chain.local_key_id()),
            c.thumbprint,
        );
    }

    /// Proves the encryption and MAC are actually applied. An unencrypted
    /// PKCS#12 opens under *any* password, so without this the round-trip test
    /// above would pass just as happily over a plaintext bundle.
    #[test]
    fn the_pfx_does_not_open_under_the_wrong_password() {
        let c = generate_self_signed("My App", 365).unwrap();
        assert!(p12_keystore::KeyStore::from_pkcs12(&c.pfx_der, "").is_err());
        assert!(p12_keystore::KeyStore::from_pkcs12(&c.pfx_der, "not-it").is_err());
        assert!(
            p12_keystore::KeyStore::from_pkcs12(&c.pfx_der, &c.pfx_password).is_ok(),
            "premise: the right password does open it",
        );
    }

    /// The alphabet is load-bearing, not cosmetic: this string gets pasted into
    /// a PowerShell `ConvertTo-SecureString` and an `openssl -passin pass:`
    /// argument, and a PKCS#12 password is encoded as a BMPString. Pin it so a
    /// future "nicer" alphabet cannot quietly introduce a quoting or encoding
    /// hazard. Tested directly — no RSA keygen needed.
    #[test]
    fn each_pfx_password_is_fresh_and_paste_safe() {
        let a = random_pfx_password();
        let b = random_pfx_password();
        assert_ne!(a, b, "a per-bundle password, not a constant");
        assert_eq!(a.len(), 32, "24 bytes as unpadded base64url");
        assert!(
            a.chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
            "ASCII, and free of shell/URL metacharacters: {a}",
        );
    }

    /// The daily rolling log writes whatever a `?value` in a `tracing` macro
    /// produces, so a derived `Debug` here would put a plaintext private key on
    /// disk. The bundle and its password are the same secret in another wrapper.
    #[test]
    fn the_generated_cert_debug_redacts_every_secret() {
        let c = generate_self_signed("My App", 365).unwrap();
        let dbg = format!("{c:?}");
        assert!(!dbg.contains(&c.pfx_password), "{dbg}");
        assert!(!dbg.contains("PRIVATE KEY"), "{dbg}");
        // The thumbprint is not a secret — it is the whole point of the reveal.
        assert!(dbg.contains(&c.thumbprint), "{dbg}");
    }

    #[test]
    fn rejects_empty_common_name() {
        assert!(generate_self_signed("   ", 365).is_err());
    }

    #[test]
    fn rejects_validity_below_one_day() {
        assert!(generate_self_signed("App", 0).is_err());
        assert!(generate_self_signed("App", -5).is_err());
    }

    #[test]
    fn rejects_validity_above_max() {
        let r = generate_self_signed("App", MAX_VALIDITY_DAYS + 1);
        assert!(r.is_err());
        // Error mentions the limit so a UI can present an actionable message.
        assert!(r.unwrap_err().contains(&MAX_VALIDITY_DAYS.to_string()));
    }

    #[test]
    fn accepts_validity_at_boundaries() {
        assert!(generate_self_signed("App", 1).is_ok());
        assert!(generate_self_signed("App", MAX_VALIDITY_DAYS).is_ok());
    }
}
