//! Graph client errors.
//!
//! Taxonomy generated by [`azapptoolkit_core::http_error_enum`] — one definition shared with
//! `ArmError`/`KeyVaultError` (previously three byte-for-byte identical hand-maintained copies;
//! see that module on why the duplication was a hazard, not just noise).

pub type Result<T> = std::result::Result<T, GraphError>;

azapptoolkit_core::http_error_enum! {
    /// Every failure mode of a Microsoft Graph call.
    pub enum GraphError {
        api_display = "graph error ({status}): {body}",
        api_code = "graph_error",
    }
}
